services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config:/mosquitto/config
      - ./.data/data:/mosquitto/data
      - ./.data/log:/mosquitto/log
    restart: unless-stopped

networks:
  default:
    name: mqtt-network

