services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config:/broker/config
      - ./.data/data:/broker/data
      - ./.data/log:/broker/log
    restart: unless-stopped
    networks:
      - mqtt-network

  server:
    image: server
    build: ./server
    container_name: server
    environment:
      BROKER_HOST: "mqtt-broker"
      BROKER_PORT: "1883"
      ROOM_TOPIC: "paho/room"
    networks:
      - mqtt-network

networks:
  mqtt-network:

