services:
  mqtt-broker:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "8883:8883"
    volumes:
      - ./broker/config:/mosquitto/config:rw
      - ./broker/data:/mosquitto/data:rw
      - ./broker/log:/mosquitto/log:rw
    restart: unless-stopped
    networks:
      - mqtt-network

  server:
    image: server
    build: ./server
    container_name: server
    environment:
      BROKER_HOST: "mqtt-broker"
      BROKER_PORT: "1883"
      ROOM_TOPIC: "paho/room"
    volumes:
      - ./logs:/usr/src/app/logs:rw
    networks:
      - mqtt-network

networks:
  mqtt-network:

